# Generated by Django 3.2.8 on 2021-11-05 12:38

from django.db import migrations, models
import django.utils.timezone
import localflavor.br.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=150, verbose_name='E-mail')),
                ('postal_code', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('address', models.CharField(max_length=150, verbose_name='Endereço')),
                ('number', models.IntegerField(max_length=10, verbose_name='Número')),
                ('complement', models.CharField(max_length=150, verbose_name='Complemento')),
                ('district', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', localflavor.br.models.BRStateField(max_length=2, verbose_name='Estado')),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
