# Generated by Django 3.2.8 on 2021-11-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
    ]
