# Generated by Django 3.2.8 on 2021-10-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
